MEX       = mex
MUMPS_DIR = $(HOME)/MUMPS

LMETISDIR = $(HOME)/METIS/metis
LMETIS = -L$(LMETISDIR) -lmetisSGI32
LPORDDIR = $(MUMPS_DIR)/PORD/lib
LPORD = -L$(LPORDDIR) -lpordSGI32
LORDERINGS = $(LPORD) $(LMETIS)

LIBSEQ  = -L$(MUMPS_DIR)/libseq -lmpiseqSGI32

LIBFORT = -L/usr/lib32 -lblas -L/usr/lib32/mips4 -lfortran

OPTC    = -O
